project:
  type: website

website:
  title: "🎯"
  description: "A blog about Machine Learning"
  site-url: "https://diegulio.github.io"
  open-graph: true
  favicon: "logo3.png"
  page-footer: "diegulio🧡2025"
  navbar:
    logo: logo3.png
    right:
      - text: "Blog"
        href: index.html
      - about.qmd
      - icon: github
        href: https://github.com/diegulio
      - icon: linkedin
        href: https://www.linkedin.com/in/dieguliomachado/
    background: "#044f31"
format:
  html:
    theme: 
      light: journal
      dark: [darkly, dark.scss]
    css: styles.css
    toc: true
    highlight-style: github  



